load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "error-reporting-cpp-macro",
    hdrs = ["src/macro/error_message.h", "src/macro/error_message_internal.h",
            "src/macro/error_message_no_param.h", "src/macro/error_message_with_param.h"],
    visibility = ["//visibility:public"],
)