load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "error-reporting-cpp",
    hdrs = ["src/error_message.h", "src/error_message_internal.h", "src/error_message_no_param.h", "src/error_message_with_param.h"],
    visibility = ["//visibility:public"],
)