load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "test-error-reporting-cpp",
    srcs = ["test.cpp"],
    deps = [
        "//error-reporting-cpp",
        "@googletest//:gtest_main",
    ],
)